version: "3"

services:
  zookeeper:
    image: debezium/zookeeper:1.3
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - sdcnet
  kafka:
    image: debezium/kafka:1.3
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - sdcnet
    environment:
      ADVERTISED_HOST_NAME: kafka
      ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ZOOKEEPER_CONNECT: zookeeper:2181
  sdc:
    image: streamsets/datacollector:3.18.1
    hostname: sdc
    container_name: sdc
    ports:
      - 18630:18630
    networks:
      - sdcnet
      # - esnet
    volumes:
      - ./volumes/sdc/data:/data
      - ./volumes/sdc/opt/streamsets-datacollector-3.18.1/streamsets-libs:/opt/streamsets-datacollector-3.18.1/streamsets-libs
      - ./volumes/sdc/opt/streamsets-datacollector-3.18.1/streamsets-libs-extras:/opt/streamsets-datacollector-3.18.1/streamsets-libs-extras
      - ./volumes/sdc/etc/sdc/sdc-security.policy:/etc/sdc/sdc-security.policy
  pgdb:
    image: debezium/postgres:12
    hostname: pgdb
    container_name: pgdb
    ports:
      - 5432:5432
    networks:
      - sdcnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ./volumes/pgdb:/var/lib/postgresql/data
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf
  dbzconnector:
    image: debezium/connect:1.3
    hostname: dbzconnector
    container_name: dbzconnector
    networks:
      - sdcnet
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
      - pgdb
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: dbzConnectConfigs
      OFFSET_STORAGE_TOPIC: dbzConnectCffsets
      STATUS_STORAGE_TOPIC: dbzConnectCtatuses
      ADVERTISED_HOST_NAME: dbzconnector
      BOOTSTRAP_SERVERS: kafka:9092

networks:
  sdcnet:
    name: sdcnet
    driver: bridge
  # esnet:
  #   external: true
